### ISSUE TITLE
Permit integration with other sign-on providers (Facebook, Google) and NDI SSO 

### ISSUE THREAD

**Issue by stigsfoot** [nditech/apollo#134]
Aha! Link: https://nditech.aha.io/features/APOLLO-200

**Comment by blynchNDI** [comment]
Removing this from project kanban 3.2, and opening it as an issue for later, as the feature does not appear to be implemented in the latest version. It is relatively lower priority however

**Comment by takinbo** [comment]
This feature has been implemented but requires that the configuration file specify settings for the oauth credentials:
```
GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET
FACEBOOK_CLIENT_ID
FACEBOOK_CLIENT_SECRET
```
