### ISSUE TITLE
searching the message log only applies to the incoming messages

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#148]
when searching for messages containing particular strings, only the incoming messages are searched.

**Comment by blynchNDI** [comment]
The search behavior for the message log is not behaving exactly as expected. Will raise this issue when further work is done on the message log

**Comment by takinbo** [comment]
The current behaviour of the message log search is to display both outgoing and incoming messages of the same conversation matching the search criteria. This was done so as to be able to view the conversation that led to a certain message being generated as response. Please re-open if this is still an issue.
