### ISSUE TITLE
Saving error when creating Apollo form 

### ISSUE THREAD

**Issue by stigsfoot** [nditech/apollo#154]
If user tries to save form without a section head, they will lose all work rather than receive a message notifying them that they need to include a section head before hitting "save."

Aha! Link: https://nditech.aha.io/features/APOLLO-120

**Comment by blynchNDI** [comment]
This is fixed in Apollo 3. Not sure if it is fixed in Apollo 2, but it is too rare a usecase to make it worth investing time in.
