### ISSUE TITLE
field co-ordinator data access

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#161]
A field co-ordinator is a participant that has special privileges to be able to login to the system and view read-only data on checklists completion statuses on the checklists page (no access to view individual data) and be able to access data on the dashboard to be able to compare their performance with that of their peers.

Aha! Link: https://nditech.aha.io/features/APOLLO-196

**Comment by blynchNDI** [comment]
Field coordinator role now exists. Additional issues are raised in #540
