### ISSUE TITLE
provide further customization of how location data is displayed

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#164]
Apollo currently supports customizing the display of administrative division data on either the dashboard and checklists/critical incidents or on the data summaries (process and results). This change would further allow for customization in the following:

1. Dashboard
2. Checklists
3. Data Summary
4. Quality Assurance

Aha! Link: https://nditech.aha.io/features/APOLLO-193

**Comment by takinbo** [comment]
Still awaiting feedback from RK. Discussion was that the current structure which is split between Data Management and Data Summarization is sufficient. @SarahCooperNDI

**Comment by SarahCooperNDI** [comment]
@takinbo Data Management and Data Summarization is sufficient -- correct.  Thanks, Tim! @blynchNDI I think we can close
