### ISSUE TITLE
display other phone numbers belonging to the participant in the checklist editing page

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#167]
Being able to contact a participant on their other numbers when the primary one is unavailable is important. This feature makes those other contact numbers visible on the checklist edit page.

Aha! Link: https://nditech.aha.io/features/APOLLO-191

**Comment by blynchNDI** [comment]
@takinbo While other phone numbers still show up on the participant page, only the most recent number is present on the checklist page. I believe we want all of the phone numbers present for an observer on the participant page to also be listed on the edit checklist page

**Comment by blynchNDI** [comment]
Didn't see at first that other phones numbers are listed in a separate row. This issue is in factf resolved.
