### ISSUE TITLE
show a log of changes made to a checklist by data clerks

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#169]
The checklist history drop-down menu isn't very useful at the moment as it displays changes made by both web interface users and text messages from participants. This change will add a tab containing the log of changes made by web interface users displaying what change was made, when it was made and by whom in addition to the normal checklist edit interface.

Aha! Link: https://nditech.aha.io/features/APOLLO-190

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI @sarahmoulton Just flagging that also listed in the Master SoW document as part of Issue 169 is "Explore whether it is possible to change history to a date and time stamp (rather than, say, six days ago)."

**Comment by blynchNDI** [comment]
Feature is implemented successfully. Any tweaks or edits to it will be opened as a separate issue
