### ISSUE TITLE
support rtl languages

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#174]
The system will need to be able to identify whether the language should read from left to
right or right to left (at present, for example, it is challenging to use the form builder in
Arabic because it continues to treat strings of text as though they read from left to right)

Aha! Link: https://nditech.aha.io/features/APOLLO-189

**Comment by blynchNDI** [comment]
Removing this from the 3.2 kanban project but leaving it open as an issue to QA once Apollo 3 is further along, and additional translations into Arabic have been done

**Comment by blynchNDI** [comment]
Full RTL/Arabic testing will be an ongoing process - I'll close this for the most moment and open individual tickets as issues are found
