### ISSUE TITLE
user interface should be responsive and accessible on mobile and tablet devices

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#177]
Apollo is currently not very accessible on mobile devices; this issue tracks progress to make it accessible on both mobile and tablet devices.

Aha! Link: https://nditech.aha.io/features/APOLLO-186

**Comment by SarahCooperNDI** [comment]
@takinbo @blynchNDI Adding this to 3.6 per our conversation today -- if this could be moved to the column we are using for work completed but awaiting feedback I think that would make sense.  Tim - please let us know if I am wrong about that!

**Comment by blynchNDI** [comment]
@takinbo - generally the mobile interface seems to be working well. Below I'll upload screenshots for the issues I've found

**Comment by blynchNDI** [comment]
![Screenshot_20190521-143804_Chrome](https://user-images.githubusercontent.com/31080607/58122083-d2b7f600-7bd6-11e9-9e5f-f107bdf46ea6.jpg)

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-21 14-49-33](https://user-images.githubusercontent.com/31080607/58122441-ac468a80-7bd7-11e9-96f4-53803f573b73.png)

The buttons under participant list are somewhat irregularly spaced and close together

**Comment by takinbo** [comment]
Interfaces (for instance the dashboard and the checklists screens) have a distinctive style from the previous and the updates are incrementally being applied. You may test those ones and provide feedback. As the others are updated, they would also be available for testing.

**Comment by blynchNDI** [comment]
The site was highly mobile responsive. A couple items were missing in various parts of the admin menu - the upload button for locations or participants set, the create form and create checklist button, and the form builder (with the form builder likely a very large lift to make mobile responsive and not worth the time it would require), but I really hope no one ever find themselves having to set up an entire event from their phone - and even if they did, they would be surprisingly close to being able to
