### ISSUE TITLE
use intuitive widgets for data entry

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#179]
Web data entry takes place via widgets (radio buttons, check boxes, etc) rather than number. "Yes" is a Yes radio button, not the number 1

Aha! Link: https://nditech.aha.io/features/APOLLO-184

**Comment by blynchNDI** [comment]
@dodumosu - I'll put this into review unless there is more that needs to be completed?

**Comment by takinbo** [comment]
moved to review.

**Comment by blynchNDI** [comment]
Dropdown menus added for multiple choice questions
