### ISSUE TITLE
have embedded help and reference tools

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#182]
Apollo should embed tooltips and other help functionality to provide guidance on complex tasks

@sarahmoulton

Aha! Link: https://nditech.aha.io/features/APOLLO-181

**Comment by takinbo** [comment]
@SarahCooperNDI @blynchNDI we've made attempts to add tooltips and generally worked on making the app more intuitive. If there are any suggestions on what we could to to improve on this, do let me know.

**Comment by blynchNDI** [comment]
@takinbo just to recap from yesterday's conversation, we'll look to provide more robust feedback as to what pages or areas could benefit from this. One initial case that comes to mind would be the Form Creation/Form Properties page (not the form builder), to explain what various fields mean that might not be readily apparent to a new user (e.g. prefix, tracking data conflicts, and votes share). Let us know if you'd like us to supply the text to be contained in the tooltips.

As a slightly separate issue, I believe you were looking to try to make more robust error messages that explain what happened when a file upload failed (things along the lines of 'this column contained an improper character', or 'this thing was missing'). Catching every single error will of course be impossible, but progress as best you can here would be very useful. Let me know if I should open a separate issue to track this.

**Comment by blynchNDI** [comment]
Attaching the screenshot below to document some of the improvements with upload error outputs

![Screenshot from 2019-08-16 11-25-51](https://user-images.githubusercontent.com/31080607/63179558-62c0dc80-c01a-11e9-98e1-6cebb81db4f7.png)

**Comment by takinbo** [comment]
@blynchNDI part of what was worked on this weekend includes help tips to explain a lot of the data input interfaces (mostly in the admin section). Do take a look and report back with your comments.

We are tracking better feedback during uploads in #160 and #176. We have an open pull request that is being reviewed and will be merged soon.

**Comment by blynchNDI** [comment]
Closing this for now as tool tips have been implemented. We can reach out at a later time regarding if we generate new tool tips to add, but presumably this will stay as is for the indefinite future.
