### ISSUE TITLE
come up with a technique (if possible) to prevent the browser from automatically saving logins

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#183]
Here's a [stackoverflow issue](https://stackoverflow.com/questions/41217019/how-to-prevent-a-browser-from-storing-password/41362874#41362874) that presents a strategy for this.

Aha! Link: https://nditech.aha.io/features/APOLLO-180

**Comment by blynchNDI** [comment]
@takinbo I noticed that when logging in, chrome still has a key icon in the url bar that when clicked on will allow you to save the password. However given that it no longer tries to save it by default, I would consider this a win and would close this issue, unless your fix is intended to totally stop chrome from saving the password in any way.

**Comment by takinbo** [comment]
@blynchNDI can you try this in Incognito mode? My suspicion is that if Chrome has a password stored, it would present the option to login with it. I did test with Chrome and didn't see the password key icon so maybe this is because I don't have a password stored.

**Comment by blynchNDI** [comment]
Ah good catch. I don't think I ever saved the password in chrome, but for some reason this seems to be tied to the fact that I've logged in previously from this google account. This doesn't seem to be occurring in fresh sessions not linked to my current google account. Marking as complete.
