### ISSUE TITLE
discuss reorganization of the user menu

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#185]
the proposed structure is:

- Set Up Events
- Participant Information
- Location lnformation
- Forms
- Users

Aha! Link: https://nditech.aha.io/features/APOLLO-178

**Comment by takinbo** [comment]
@SarahCooperNDI had a rethink about this. All of these actions are actually actions performed by administrators and so shouldn't be in the User Menu. I would say that the User Menu is currently acceptable.

**Comment by SarahCooperNDI** [comment]
@takinbo @blynchNDI Agreed the current submenus that appear at the top of the screen when you enter Admin meet this criterion -- however we have some questions for you about the Roles submenu that we can discuss on our 5/16 call before closing this issue.

**Comment by SarahCooperNDI** [comment]
@takinbo @blynchNDI Per our discussion we can close this issue once there are stable default permissions linked to each role under the Roles submenu of the Admin menu.

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-21 16-01-56](https://user-images.githubusercontent.com/31080607/58126803-ca18ed00-7be1-11e9-8221-3558c7089721.png)

I'm closing this issue under the assumption that the editable permissions for each role as shown above meet @SarahCooperNDI 's criteria

**Comment by takinbo** [comment]
There are default permissions but this will only be visible on new deployments. Existing deployments will have to update the permissions manually. This was done to prevent collisions when the migration is being applied.

**Comment by SarahCooperNDI** [comment]
Thanks @takinbo Could you share with myself, Richard, Sarah Moulton, Ben, and Johandra with the list of default permissions for each role (even if just in an email or Word doc) so we can review?  Thanks!!
