### ISSUE TITLE
users should be able to view response rates on the dashboard as bar charts in addition to pie charts

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#186]
it would also be useful to have the bar charts show the entire number of checklists expected and then vary the size of each bar based on their completion status figures. The bars should also include the figures and their percentage.

Aha! Link: https://nditech.aha.io/features/APOLLO-177

**Comment by blynchNDI** [comment]
Looks good to me. Will review with @SarahCooperNDI and @RLK-NDI , but if they have no additional feedback, I think this can be closed.
