### ISSUE TITLE
percentages on the pie chart on the dashboard should be displayed outside of the pie chart if it's less than 10%

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#187]
If the percentage is 0%, completely hide the display of the percentage.

Aha! Link: https://nditech.aha.io/features/APOLLO-176

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu After reviewing the new 3.0 dashboard, we would actually like to modify this issue. The percentages can remain on top of the pie chart but could they please be made **bold**? At present the percentages are a bit hard to read, especially for missing messages (see below).

![Percentages to Bold](https://user-images.githubusercontent.com/48285413/59949252-929b9b80-9440-11e9-8260-117fc8345897.png)

**Comment by takinbo** [comment]
Scheduled for [3.8](https://github.com/nditech/apollo/projects/12)

**Comment by blynchNDI** [comment]
Percentages stay outside of the pie chart until 10%
