### ISSUE TITLE
users should be able to filter checklists by the "any" filter option

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#193]
The _any_ filter option will provide filtering by boolean _OR_ of any of the text message groups e.g. _any partial_ would mean any of the text message groups has a partial response; _any missing_ would mean filter by any of the text message groups having a missing response.

Aha! Link: https://nditech.aha.io/features/APOLLO-170

**Comment by blynchNDI** [comment]
According to @SarahCooperNDI , this issue should also allow for an option to filter for all participants that have any missing data on their checklist (for use at the end of election day). I.e., there should be a way to filter for 1)all participants with missing data for a section, 2)all participants with partial data a section, or 3)all participants who have missing or partial data for any section.
 
This functionality could possibly be folded into the AND/OR conjunction field.

**Comment by takinbo** [comment]
I believe we discussed that this last use case (missing OR partial) will be clumsy to implement; not because we can't issue the query but that the user interface will be non-intuitive. Recommendation is to train users to filter by ANY missing and subsequently, ANY partial.

**Comment by SarahCooperNDI** [comment]
@takinbo even if we agree on that as a fix unless we are running old version of the code for the QA site at present there is no option to filter by ANY missing or ANY partial. I am attaching screenshots of the options we have. We can filter particular messages based on whether they are missing or partial - as has always been the case - but we cannot filter based on whether ANY messages are missing or ANY messages are partial. I would suggest embedding these options in the same drop-down menu with the AND conjunction.

![No Option ANY missing or ANY partial](https://user-images.githubusercontent.com/48285413/57385872-42fb5c00-7181-11e9-93e2-28ac947671f5.png)

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-21 15-46-22](https://user-images.githubusercontent.com/31080607/58125880-a0f75d00-7bdf-11e9-919d-65bb961cc6a3.png)

@SarahCooperNDI this is the latest iteration - is this in line with what you want?

**Comment by blynchNDI** [comment]
@takinbo or @dodumosu , could you change the toggle so that it is in the middle of "and" and "or" . Something like:

AND <toggle button> OR

where moving the toggle between the two would change it from "and" to "or". @SarahCooperNDI are "AND" and "OR" good labels, or would you rather use other labels?

**Comment by takinbo** [comment]
@blynchNDI that would not be a toggle. The colour change of the widget is like an On or Off button and has a different intuitive meaning if it is used to represent a "direction". The alternative was to use a dropdown option but that also has its drawbacks.

**Comment by blynchNDI** [comment]
Talked with @SarahCooperNDI and she agreed that the feature as currently implemented is good
