### ISSUE TITLE
provide pagination to navigate through checklists directly within the checklist edit page

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#196]
Whatever was the filter that was used to retrieve the checklists should be preserved when using the pagination next and previous buttons or links.

Aha! Link: https://nditech.aha.io/features/APOLLO-167

**Comment by takinbo** [comment]
Thanks @cdoten. The issue with this approach is that by the time the clerk is done updating a record, the situation as regarding the "next" record might have changed (another data clerk might have updated it or data might have come in from the observer). What we could do is preserve the query parameters so that when the record is saved, the data clerk is sent back to the list with the filter parameters preserved so they can work on the next record. Will this suffice?

**Comment by cdoten** [comment]
That wouldn't be as good, but I do see the difficulty, and it would be a
big step forward to return to the same search if it wasn't doing that
already.

**Comment by blynchNDI** [comment]
Page numbers exist for moving between pages of filtered data, and can be navigated between without losing the filter. The filter also updates with every click to include changes in data (e.g. if you are filtering for partial entries and a new entry becomes partial, it will then be added to the filtered list when you refresh or move to the next page)
