### ISSUE TITLE
add support for a string form element that takes numeric digits but doesn't treat them as numbers

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#201]
This will allow the system to parse and store numeric data that may contain leading zeroes without truncating them.

Aha! Link: https://nditech.aha.io/features/APOLLO-162

**Comment by blynchNDI** [comment]
There is now the ability to specify whether a number question should be treated as a number or text. If it is treated as text, it allows characters other than numbers to be submitted however. @SarahCooperNDI do we want to prevent a non-number (e.g. letters) from being submitted? (If so, I imagine Apollo could run a convert to number on the text string to verify that is indeed a number, before storing it as a text string)

**Comment by takinbo** [comment]
You're right @blynchNDI it shouldn't take non-numeric input even if it is treated as text. Will submit a patch for this.

**Comment by blynchNDI** [comment]
Ok, moving this back into To Do just so I know when it's ready to be reviewed again

**Comment by takinbo** [comment]
A fix has been deployed that fixes this behaviour.

**Comment by blynchNDI** [comment]
Confirmed that numbers as text fields will prevent you from submitting anything other than numbers - they work not only with integers, but even will verify that a number is a valid decimal
