### ISSUE TITLE
provide a more visible hint for questions that fail a verification check (maybe a red flag?)

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#209]
Aha! Link: https://nditech.aha.io/features/APOLLO-154

**Comment by dodumosu** [comment]
![Edit_Submission_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/56666530-01a87e00-66a4-11e9-9e4d-51e3cc853a98.png)
![Edit_Submission_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/56666569-11c05d80-66a4-11e9-96d4-eb300dda65d6.png)
![Edit_Submission_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/56666599-256bc400-66a4-11e9-8e87-5b56c61a5aad.png)
@SarahCooperNDI i'm not certain these work. any suggestions for improving them?

**Comment by blynchNDI** [comment]
@SarahCooperNDI could you further explain or note whether this has been implemented? Currently, the feature is that a note appears when you edit a checklist entry, telling you which QA checks it failed.
![Screenshot from 2019-05-01 17-10-12](https://user-images.githubusercontent.com/31080607/57043144-bd355900-6c34-11e9-8f2f-b12320c01296.png)

**Comment by takinbo** [comment]
![screenshot-1556844853](https://user-images.githubusercontent.com/41004/57115429-7cc20200-6d3e-11e9-8156-534067c8f4c6.png)

No. This is how it is displayed. The screenshot @blynchNDI shared shows the QA validation error summary, each question now gets highlighted also if it fails a QA check.

**Comment by blynchNDI** [comment]
Ah perfect, looks good
