### ISSUE TITLE
for questions that include string or control variables, the data summary should only show the number REPORTED and the number MISSING

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#220]
Essentially every question will now have at least a report showing the number reported and the number missing.

Aha! Link: https://nditech.aha.io/features/APOLLO-143

**Comment by blynchNDI** [comment]
(Currently questions with text responses cannot be added to the process analysis)

**Comment by blynchNDI** [comment]
@dodumosu the new analysis options should solve this, with the user now able to choose between 'Count' and 'No Analysis'. However when selecting 'Count' on the form builder page and then clicking save, the analysis selection seems to revert to 'No Analysis' no matter what. Once that's fixed though, this should be done.

**Comment by takinbo** [comment]
I'm unable to replicate this. What question type are you using? Please attach screenshots of both the form builder and the analysis.

**Comment by blynchNDI** [comment]
Perhaps this only occurs when a checklist has already been created, and a question is then added later? This occurs when using the Comment question type. Editing the question in the form builder will allow you to choose 'Count' as the analysis type, and after hitting Save for editing question, the analysis type will still be 'Count' if you return to this question without leaving the form builder. However after clicking Save to exit the form builder, the analysis type seems to always be 'No Analysis' when you return to the form builder. This doesn't seem to be an issue for any other question type.

![Screenshot from 2019-08-10 15-17-52](https://user-images.githubusercontent.com/31080607/62825965-1ab93a00-bb82-11e9-98c0-2004b7b10c34.png)

![Screenshot from 2019-08-10 15-19-45](https://user-images.githubusercontent.com/31080607/62825998-7388d280-bb82-11e9-8557-7d7ddd5b8bcc.png)

**Comment by dodumosu** [comment]
noted. a fix has been put in place and will be merged soon

**Comment by takinbo** [comment]
#473 has been merged.

**Comment by blynchNDI** [comment]
Can successfully set analysis as either 'Count' or 'No Analysis'
