### ISSUE TITLE
explore possibility of dynamic definition of participant columns

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#224]
participant ID, all levels of the location level hierarchy (that are enabled for display, except for the top level), role, primary phone number must always be visible.

Aha! Link: https://nditech.aha.io/features/APOLLO-139

**Comment by SarahCooperNDI** [comment]
@takinbo @blynchNDI Per our conversation today, I believe this issue can be closed.

**Comment by blynchNDI** [comment]
Closing per Sarah C's comment
