### ISSUE TITLE
participant evaluation

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#226]
- adopt a 1-5 ranking system versus stars so that the rankings could be exported
- in collaboration with the NDI Elections Team, develop clear criteria for how participants are ranked – at present Accuracy and Completion are not intuitive
- columns should match participant file and then include columns for each metric

Aha! Link: https://nditech.aha.io/features/APOLLO-137

**Comment by SarahCooperNDI** [comment]
Current task in 3.8 Kanban is to disable this feature in the code base

**Comment by blynchNDI** [comment]
feature is no longer present as requested
