### ISSUE TITLE
change the font to include a slashed zero (and a European 7)

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#228]
has been implemented, but requesting feedback. displayed typeface supports Arabic, which was why it was chosen, as monospaced typefaces are the kind to support slashed (or, in this case, dotted) zeroes

![messages_-__private_browsing_](https://user-images.githubusercontent.com/1408662/53296047-f81baa80-3807-11e9-8c56-ac1e0020fe99.png)

Aha! Link: https://nditech.aha.io/features/APOLLO-135

**Comment by takinbo** [comment]
It was concluded that the currently chosen font will suffice.
