### ISSUE TITLE
change the DISPLAY so that In and Out (i.e. message and response) appear on the same line

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#229]
![messages_-__private_browsing_](https://user-images.githubusercontent.com/1408662/53296044-dfab9000-3807-11e9-938c-60ce3fdc524e.png)

to avoid horizontal scrolling, pairing a message with its response as above was chosen as a possible solution. inbound messages that do not have a reply, or text blasts will have an empty alternate row.

recommending putting *Mobile* as the first column and making that span both rows.

Aha! Link: https://nditech.aha.io/features/APOLLO-134

**Comment by SarahCooperNDI** [comment]
@dodumosu @takinbo @blynchNDI Just conferred with Richard and we are both happy to group the inbound and outbound messages as you propose.  I also like the idea of putting Mobile as the first column.  Thanks!

**Comment by SarahCooperNDI** [comment]
Can we ensure that there is always an Outgoing field grouped with an Incoming message (even if that field is blank)? The idea behind having the incoming and outgoing messages move to the same line was to be able visually to verify rapidly identify incoming messages that have not yet received a reply from the system.

![Group Incoming and Outgoing Messages Together](https://user-images.githubusercontent.com/48285413/61823620-22f74280-ae2a-11e9-8023-463241405783.png)

**Comment by blynchNDI** [comment]
Looks good - The only thing I just noticed is that the outgoing messages appear below the incoming ones, and given that the message queue is organized chronologically in order from most recent at the top to earliest at the bottom, it would make sense to put the outgoing messages above (and thus after) the incoming ones. Hopefully that's an easy change to make

**Comment by blynchNDI** [comment]
It would also be good to have the same change applied to message log under the edit checklist page

**Comment by takinbo** [comment]
resolved in #449
