### ISSUE TITLE
enable more detailed, robust message search including boolean logic

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#230]
Aha! Link: https://nditech.aha.io/features/APOLLO-133

**Comment by SarahCooperNDI** [comment]
We want to be able to use AND/OR logic when querying the message log.  For example find all messages containing "Please send" AND "SMS 4".  Right now we can only query on a single text string.  Does that make sense?

**Comment by takinbo** [comment]
#451 tackles this problem by enabling full text search. You would be able to search for terms within the text by specifying all the different parts (e.g. `Please send SMS 4` will search for all text messages containing the terms `Please`, `send`, `SMS` and `4` in no specific order).

Unfortunately, we would either have to use an external application (e.g. elasticsearch) or implement complex logic if we would support both AND and OR type queries with the default that is currently available and so will be a heavy lift. If the OR case is critical and we have sufficient time, we can revisit this.

**Comment by blynchNDI** [comment]
The search functionality appears to be working as described per @takinbo 's comment. Will move this to 3.12 as more of an optional feature perhaps useful if time permits. In addition to including OR functionality, there may be a use case for being able to group text using quotes when it is desired to search for grouped strings (e.g. right now, searching for `please send` will currently bring up anything with `please` and `send` in it, whereas there might be a use case for also wanting to search for `"please send"` in quotes which would mean `please send` would have to appear consecutively in the message.) Not sure if this is an easy fix, or would require the same complications as implementing OR.

**Comment by blynchNDI** [comment]
Closing this, as functionality is done, and there isn't time for additional work on this
