### ISSUE TITLE
latitude and longitude can be displayed on the checklist index page

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#234]
see #232

Aha! Link: https://nditech.aha.io/features/APOLLO-129

**Comment by blynchNDI** [comment]
The location is now recorded on the checklist page with a blue icon, and clicking on it provides a map showing the location. During our call we discussed whether the location should be editable, settling on probably not. The coordinates could in theory also be displayed somewhere, although the map seems much more useful than coordinates would be. Will consult with our client next week on this, but likely this is done.

**Comment by blynchNDI** [comment]
@takinbo or @dodumosu , would it be easy to add the coordinates to the top of the pop-out box with the map as shown below?

![Screenshot from 2019-07-16 15-48-58](https://user-images.githubusercontent.com/31080607/61324937-91605300-a7e1-11e9-8d8c-b1c00377b2e7.png)

**Comment by takinbo** [comment]
I am unconvinced that displaying the actual co-ordinates provides any utility even though it would be trivial to do so. I fail to see how it would provide any useful information. I believe that the utility to capturing that information is to be able to see where the observer was when the report was captured. Could you elaborate how providing the actual co-ordinates would be used in practice?

**Comment by blynchNDI** [comment]
Fair point. Will discuss during our meeting tomorrow with @SarahCooperNDI and @sarahmoulton to see whether or not there is a valid use case here

**Comment by blynchNDI** [comment]
Per our conversations, displaying coordinates would either not be used or else cause more confusion. A better feature would be a location-based quality assurance check down the line that verified the observer was within a certain distance of the polling station's coordinates
