### ISSUE TITLE
enable more detailed, robust search including boolean logic for phone numbers

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#235]
for participants and checklist views.

Aha! Link: https://nditech.aha.io/features/APOLLO-128

**Comment by SarahCooperNDI** [comment]
@dodumosu and @takinbo -- Exactly. A use case, for example, would be an observer that has been known to use two phone numbers.  We want to be able to, say, find all messages in the message log sent using either phone number 1 OR phone number 2.  Does that make sense?

**Comment by takinbo** [comment]
After reviewing the solution @dodumosu worked on, I'm inclined to think that the only time it would be useful is exactly that one use case - being able to find all messages sent or received by a set of phone numbers. So it would be phone1 OR phone2, etc. I don't see how phone1 AND phone2 ever makes sense. I would suggest allowing the supply of a group of phone numbers separated by a space or comma to allow searching of messages from any of the supplied phone numbers. @SarahCooperNDI?

**Comment by takinbo** [comment]
The current implementation now allows specifying multiple phone numbers to search the message log by so you can search the message log by all the phone numbers known for an observer.

**Comment by blynchNDI** [comment]
Typing in multiple phone numbers in the message search bar now searches for messages sent by any of the numbers inputted
