### ISSUE TITLE
integrate a section under the participant record where it is possible to see ALL of the phone numbers associated with that particular individual

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#236]
![edit_participant_ _400011_-__private_browsing_](https://user-images.githubusercontent.com/1408662/53296014-7a579f00-3807-11e9-8f7f-d9bd5aba0b7e.png)

"All Phones" header is collapsible

Aha! Link: https://nditech.aha.io/features/APOLLO-127

**Comment by blynchNDI** [comment]
@SarahCooperNDI - This feature has been implemented, although in response to the requested bug fix, when new participant phone numbers are uploaded, all old ones are lost - just want to verify that this is in line with what you are looking for. It makes sense if we consider the participant list upload to be a clean slate, and assume that all relevant phone numbers will be located in the new participant upload.
