### ISSUE TITLE
improve granularity of logical check verification

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#237]
Users can currently only verify that a checklist is valid for *all* logical checks. This enhancement will allow a user to verify a checklist for a singular logical check at a time.

Aha! Link: https://nditech.aha.io/features/APOLLO-126

**Comment by SarahCooperNDI** [comment]
I believe Tim/Richard/I are all on the same  about how this should work.  We want the ability to verify each individual question in the QA Check such that once verified the QA flag would switch to a different icon signifying verified.  I think an example will make this the easiest:

- Say we have two QA Checks: AD>3 and AD<BD
- Our observer texts in AD = 4
- This should trip the QA check AD>3
- If we call the observer back and verify question AD, then the QA check AD>3 should switch to verified
- Let us say that the observer then texts in BD=4
- The QA check AD<BD should be flagged, but we should see that the response to AD has already been verified.  The data clerk would then need to call back on BD only and once the response to BD has also 
been verified then the QA check AD<BD should change from flagged to verified

Does this make sense? Is it feasible?

**Comment by takinbo** [comment]
#430 was just merged that addresses this issue. Now each question can be independently verified and if all questions are verified, then that quality assurance criterion becomes verified.

**Comment by blynchNDI** [comment]
Looks good to me. The only thing I could think of is having the verification for each question be independent from a separate verification that the fact that the logical check not passing is ok, and that it can be ignored. E.g. if the data clerks calls the observer and they verify all three questions/fields involved in a quality assurance check, but it still seems like something's wrong, you might one to indicate that all 3 of these fields were verified, but that we don't want to say that the quality assurance fail can be ignored yet. I'll leave it to @SarahCooperNDI or @RLK-NDI though to specify whether there is actually a need for this in real life situations - it might be a better workflow just to document in the comments what's going on for any case in which a QA check is Verified

**Comment by takinbo** [comment]
A QA condition being marked as verified indicates that it fails but the responses for the condition have been verified so could be ignored. I think the workflow issue is mostly concerning training.

**Comment by blynchNDI** [comment]
Ok makes sense. Will close and reopen only if there are requests from elections team to change this
