### ISSUE TITLE
add API interfaces to provide access to data artefacts

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#239]
data artefacts may include submissions (checklists and critical incident reports), participant data, location data, admin divisions, messages and forms.

Aha! Link: https://nditech.aha.io/features/APOLLO-124

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI Just realizing this was assigned to 3.3 Kanban but never closed.  What is the current status of this issue please?

**Comment by takinbo** [comment]
It's still outstanding. Let's plan to schedule it in on a future sprint.

**Comment by takinbo** [comment]
API interfaces are fully documented and can be tested from the swagger endpoint at /swagger-ui/

**Comment by blynchNDI** [comment]
API has been tested, and calls appear to be working. Will add documentation for using it at a later date.
