### ISSUE TITLE
Create linkage to external CRM system to push and pull details for individual participants, including name, phone, organizational affiliation, home address, and email address. Be able to update custom CRM user fields with participant "scores" and notes

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#240]
Aha! Link: https://nditech.aha.io/features/APOLLO-123

**Comment by takinbo** [comment]
We currently have an API that can be integrated with external applications. Would be useful to get an idea of an actionable goal for this issue. @blynchNDI @SarahCooperNDI @sarahmoulton

**Comment by takinbo** [comment]
#507 currently adds additional name fields (first name, other names and last name) in addition to renaming the legacy name field to full name. Teams using this software have the option of uploading legacy data to the full name field or upload data individually as first name, last name and other names. Names are displayed in the order: firstname, othernames and lastname. In a situation where a different order is preferred, the suggestion will be to upload the data in a different order.

**Comment by blynchNDI** [comment]
Verified that a test import into Civi works. Just need to fully test out the 3 names vs 1 name feature, and then this should be ready to be closed

**Comment by blynchNDI** [comment]
First, middle, and last name schema is working as expected. These fields remain separate for uploading and editing within Apollo, but display concatenated. When a Full Name is added, it overrides these, and when a full name is deleted, it reverts to the first, middle, last
