### ISSUE TITLE
Cannot deselect other language option in Deployment settings

### ISSUE THREAD

**Issue by sarahmoulton** [nditech/apollo#242]
![screen shot 2019-02-24 at 8 11 53 am](https://user-images.githubusercontent.com/8295355/53296266-f8b64000-380b-11e9-8fc9-c7052faa27c0.png)

Aha! Link: https://nditech.aha.io/features/APOLLO-122

**Comment by blynchNDI** [comment]
Looks like this has been addressed, @sarahmoulton see if this matches with what you were looking for

**Comment by takinbo** [comment]
@sarahmoulton please re-open if this solution is not satisfactory.
