### ISSUE TITLE
uploading data for a participant does not replace phone numbers

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#255]
Currently when uploading participant data, rather than replacing phone numbers, it only adds to the phone numbers already configured for the participant. This is not the expected behaviour.

As a data manager, whenever I re-upload participants to the system, it should replace the phone numbers with whatever was in the file.

**Comment by blynchNDI** [comment]
Tested. When a new participant list uploaded with new phone numbers, the new phone numbers replace the old ones.
