### ISSUE TITLE
Long question descriptions can render submission data unreadable in edit

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#292]
Somewhat related to #179, though not directly. When question descriptions are very long, it can render the text field widgets currently used for data entry so small that the text inside cannot be seen.

![QsCIn6VgQu](https://user-images.githubusercontent.com/1408662/57083452-7b69e880-6cf0-11e9-9743-0495807c398e.png)

**Comment by takinbo** [comment]
@dodumosu can you confirm if this is still the case in Apollo 3?

**Comment by dodumosu** [comment]
It seems not to be. Please see attached screenshot
![Screenshot_2019-06-17 Edit Submission](https://user-images.githubusercontent.com/1408662/59602140-f00cb100-90fd-11e9-8072-b895029f4a06.png)

**Comment by takinbo** [comment]
With the updated design, this is no longer an issue.

**Comment by blynchNDI** [comment]
Confirmed that this is no longer an issue - the text box stays a constant size
