### ISSUE TITLE
Updated observer phone numbers should persist as the default #

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#301]
BUG FIX: If a clerk edits a participant record to save a new phone number or verifies a phone number that an observer uses this number is currently saved as Phone #2.  The last phone number to be associated with a particular participant should always save as Phone #1 (whether this information comes from a clerk, from verifying a phone number or from uploading a new participant file).  Otherwise we will continue to text blast observers on old phone numbers.

**Comment by blynchNDI** [comment]
The most recent verified phone number is now the default phone number listed at the top and the one that text blasts are sent to
