### ISSUE TITLE
BUG FIX: If multiple participants use a phone number (for example paired observers sharing phone) editing the phone number for one participant or removing the phone number from the list of verified phone numbers for that participant causes the edit to carry over to ALL observers who have ever used that phone number.

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#302]
Deleting a phone number from the list of verified phone numbers for one participant should not cause it to delete from the list of verified phone numbers for all participants who have ever used that number

**Comment by blynchNDI** [comment]
Deleting a phone number for one observer no longer affects the same phone number for another participant
