### ISSUE TITLE
Dashboard Features from Apollo 2.x to Carry Over to Apollo 3.x

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#305]
At present the dashboard in Apollo 3.x cannot be filtered by location or sample.  This feature from Apollo 2.x should be migrated to Apollo 3.x

**Comment by blynchNDI** [comment]
Location filtering is present and working. The sample field is also present, though I don't think it's possible to add samples on the frontend to test whether it's working.
