### ISSUE TITLE
Font Standardization

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#308]
We should move to two fonts -- one monospaced or fixed-pitch font, which will be especially useful for phone number lengths -- and one other font (serif or sans serif)

**Comment by blynchNDI** [comment]
Phone numbers appear to be using a monospaced font. @SarahCooperNDI can you confirm that the font overall is acceptable?

**Comment by SarahCooperNDI** [comment]
Looks good to me thanks @blynchNDI @takinbo
