### ISSUE TITLE
Caution Icon Standardization

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#309]
The same yellow caution icon should be used for all instances where it appears on the checklist landing page (see below screenshot for example of two different caution icons).

![Multiple Yellow Caution Icons](https://user-images.githubusercontent.com/48285413/57410414-b9678080-71b8-11e9-9a6b-3cab71e42db0.png)

**Comment by blynchNDI** [comment]
Yellow triangles and green checks match
