### ISSUE TITLE
Primary Phone Number Added to Participant Record

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#310]
The Primary Phone should be added to the participant record next to the observer name in parentheses (please see below screenshot)

![Screenshot Where Primary Phone Should Appear](https://user-images.githubusercontent.com/48285413/57410816-d6e91a00-71b9-11e9-9acb-68ea81797b46.png)

**Comment by blynchNDI** [comment]
Feature is implemented
