### ISSUE TITLE
Verification Button for Phone Numbers Enhancement

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#311]
It should be possible to click to unverify a phone number if a clerk accidentally clicks to verify a phone number

**Comment by blynchNDI** [comment]
On the edit checklist screen, the verification button for phones can now be clicked through multiple times to toggle between verified and unverified. Looking for feedback from @SarahCooperNDI on two things:
1) Do we need to make the toggle capability more obvious (someone less familiar with Apollo might not know to click multiple times to verify/unverify)
2) Currently, only the most recent phone number can be verified/unverified. I would recommend verification/unverification also be allowed on the participant page (with a similar system where you can click the green/red circle multiple times to verify/unverify)

**Comment by blynchNDI** [comment]
feature is implemented - can toggle verification on and off. For the future, might look into implementing the verification button on the participant page
