### ISSUE TITLE
Bug Fix: .XLSX Location Uploads Fail

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#314]
See attached the file we tried to upload as .xlsx and received an error.  When we converted to .CSV the upload worked fine.  The .XLSX file is attached. (GitHub apparently won't support a .CSV attachment but I can share over email if that version is also useful)

[Tunisia Locations.xlsx](https://github.com/nditech/apollo/files/3174212/Tunisia.Locations.xlsx)

**Comment by blynchNDI** [comment]
Upload is now working
