### ISSUE TITLE
Bug fix: Any Locations Ticked to be Visualized in ANY Location Set Show in Participants

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#315]
Under participants, locations show from location sets that have not been associated with those participants.  In the screenshot below Governorates (27) is pulling from the location set Tunis Governorates Test because that level was selected to be displayed in participants in the Tunis Governorates Test location set. However these participants have been associated with the Test Location Set, which does not have Governorates in its administrative divisions. (Also attaching screenshots of the two location sets).

![Location Bug Under Participants](https://user-images.githubusercontent.com/48285413/57644609-7d526800-758a-11e9-9c92-e4c56153d2cd.png)

![Test Location Set](https://user-images.githubusercontent.com/48285413/57644926-2c8f3f00-758b-11e9-8c10-327b5e63dafe.png)

![Tunis Governorates Test Location Set](https://user-images.githubusercontent.com/48285413/57644942-33b64d00-758b-11e9-9947-0145bff74148.png)

**Comment by blynchNDI** [comment]
The issue is no longer appearing where it was previously found. Will close now, while also keeping an eye out for it when creating new events in the next couple of days, just to make sure the issue is indeed fully resolved.
