### ISSUE TITLE
Bug Fix: Arabic Exports and Imports Not Working Properly

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#316]
The Arabic locations that we imported into the Tunis Governorates Test location set are not rendering properly -- they show as ???? except for the governorates of Tunis 1 and Tunis 2, Sfax 1 and Sfax 2 and Nabeul 1 and Nabeul 2, which show as ???? 1 and ???? 2

![Arabic File Imports Do Not Read Properly](https://user-images.githubusercontent.com/48285413/57652214-112d2f80-759d-11e9-9dfb-20f6730a01c4.png)

**Comment by dodumosu** [comment]
I think we can close this as an encoding issue and update the documentation (and possibly the interface) that the encoding must be UTF-8 for CSV files. I checked the mimetype of the file that was uploaded, and it was US-ASCII:
![Screenshot from 2019-05-17 18-38-24](https://user-images.githubusercontent.com/1408662/57946010-35f21180-78d3-11e9-8eef-678df7b933d7.png)

**Comment by dodumosu** [comment]
I think we should update the documentation (and possibly the interface) to mention that CSV import files should be encoded in UTF-8. I took the liberty of checking the CSV file that was uploaded, and found that it was encoded in US-ASCII, which doesn't support Arabic characters.

**Comment by SarahCooperNDI** [comment]
#361 needs to be addressed before this can be reviewed

**Comment by SarahCooperNDI** [comment]
Saved the below Excel file as a comma delimited CSV and added UTF-8 encoding under web options. The CSV still isn't properly reading the Arabic. Thoughts?

Tunisia Locations UTF 8 - 20190531.zip

Tunisia Locations UTF 8 - 20190531.xlsx

**Comment by dodumosu** [comment]
So I downloaded both files. The CSV is ASCII, which won't encode Arabic characters. The second CSV (from the desktop) was an export from the Excel spreadsheet in UTF-8 for comparison.

![1__dipoodumosu_Dipos-MacBook-Pro____Downloads__zsh__and_Bug_Fix__Arabic_Exports_and_Imports_Not_Working_Properly_·_Issue__316_·_nditech_apollo_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/61181214-ef8f0980-a61a-11e9-98b7-22d1cebd908a.png)

@sarahmoulton @blynchNDI your thoughts?

**Comment by blynchNDI** [comment]
Seems to be working, but will do further testing

**Comment by blynchNDI** [comment]
Everything seems to be working so far - will test arabic compatibility more completely as part of #174
