### ISSUE TITLE
Bug Fix: Location Names Do Not Pull from Admin Divisions in Non-English Interfaces

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#317]
When account settings have been switched to a language other than English, the location names on the Participant menu do not render. Presumably they should still pull from Administrative Divisions (in whatever language the administrative divisions have been set even if that is not the language of the interface?)

![In Other Language Interfaces Location Names Not Pulling Properly](https://user-images.githubusercontent.com/48285413/57652639-02934800-759e-11e9-8c9f-ff1aa14c5bff.png)

**Comment by blynchNDI** [comment]
@takinbo there still appears to be a lingering issue as seen in the screenshot below. For example if the user's language is changed to spanish, and the location names were not uploaded in spanish, then they display as None. The desired state would be to have the system use the translated location names if they were uploaded in the current language (e.g. if the user has selected spanish as the current language, use the spanish names if they were uploaded), but if names were not uploaded to the current language, to default to the any language that the locations were uploaded in (e.g. if the locations were uploaded in French or Arabic, the system would choose one of these two to render the name if the user has selected spanish as the language).

![Screenshot from 2019-05-21 16-50-33](https://user-images.githubusercontent.com/31080607/58129781-8fff1980-7be8-11e9-82da-c1c4a6a6765c.png)

**Comment by takinbo** [comment]
Can you test this again. I can't seem to replicate the issue.

**Comment by blynchNDI** [comment]
The sequence of actions I did before is no longer replicating this, possibly because of a recent code push. Will mark as closed, and reopen if the issue reappears.
