### ISSUE TITLE
Add the "Add Filter" Search Function Under Events to Participants and Locations

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#318]
The "Add Filter" search function under events is great -- would it be possible to add it to the participant and location sets as well?

![Add Filter Search Feature](https://user-images.githubusercontent.com/48285413/57653138-1be8c400-759f-11e9-9313-d4956251c580.png)

**Comment by blynchNDI** [comment]
The add filter function is now present and working for participant and location set. Will reopen if it is decided that there should be any modifications to it.
