### ISSUE TITLE
Location Sets do not Need an "Add Extra Field" Option

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#319]
Since location fields are determined by the Administrative Divisions we think the best way to add an "extra" location field would be by modifying Administrative Divisions and this option can drop out for the Location Sets although it should be kept for the Participant Sets.  (Unless there is a use case for "Add Extra Field" under locations that we are not thinking of?)

![Add Extra Field Location Sets](https://user-images.githubusercontent.com/48285413/57654487-4ab46980-75a2-11e9-9979-926bd67fa3b1.png)

**Comment by takinbo** [comment]
Extra fields allow us to capture metadata that is not part of regular data captured for locations that may be available in a deployment and may be useful in places like QA. In the past, we've used this to capture the elections commission coding for polling stations that was different from what the partner was using and was used to confirm that the observer was in the correct location.

**Comment by blynchNDI** [comment]
That makes sense to me - this feature is useful for situations in which we want to add additional information about locations that doesn't belong in the location hierarchy. As per Tim's example, it would probably be confusing to create a separate level in the location hierarchy for extra names for the polling stations. @SarahCooperNDI do you agree?

**Comment by SarahCooperNDI** [comment]
@takinbo @blynchNDI I agree! We can close this issue.
