### ISSUE TITLE
Menu Structure Should Show "Admin" Options When Conducting Admin Tasks

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#320]
When we enter into participant or location sets through Admin, the menu reverts to the menu structure for an active deployment.  Can it instead be the Admin menu structure that is preserved at the top (Deployment, Events, Users, Roles, Location Sets, Participant Sets, Forms)?

Admin Menu Structure (should display when entering into participant and location sets from the admin menu)

![Menu Structure for Admin Tasks](https://user-images.githubusercontent.com/48285413/57656759-4e96ba80-75a7-11e9-8231-4236a802e1d4.png)

Menu Structure for Active Deployments (should display when viewing participants and administrative divisions from an actively deployed event)

![Menu Structure for Active Events](https://user-images.githubusercontent.com/48285413/57656874-ab927080-75a7-11e9-9884-c8de244bb59a.png)

**Comment by SarahCooperNDI** [comment]
Data Summary and the Quality Assurance dashboard still include the old menu structures (see below)

![Data Summary Menu Structure (Old Menu)](https://user-images.githubusercontent.com/48285413/60359933-6fc13800-99a8-11e9-895f-88a8ca63bfb1.png)

![Quality Assurance Menu Structure (Old Menu)](https://user-images.githubusercontent.com/48285413/60359948-7bacfa00-99a8-11e9-8a40-9606791d22de.png)

@takinbo @dodumosu @blynchNDI

**Comment by takinbo** [comment]
These screens are not admin related but will be converted when we get to treat QA specific tasks. If after going through the admin menu, there are no further comments or bugs, this issue can be closed.

**Comment by blynchNDI** [comment]
Confirmed that all admin pages maintain the admin menu at the top
