### ISSUE TITLE
QA search error

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#323]
On the ApolloQA site, when going to the quality assurance page for ".. . .F.orm..", choose "CA to CB" under Quality Check Criterion and choose Quality Check Condition "Flagged", and then click Filter. This leads to an error where the server does not send back a response.

The nginx error is listed below:

2019/05/16 15:17:00 [error] 2550#2550: *60329 upstream prematurely closed connection while reading response header from upstream, client: 172.68.65.57, server: apolloqa.demcloud.org, request: "GET /submissions/qa/4?participant_id=&sample=&location=&quality_check-criterion=0&quality_check-condition=2&quarantine_status= HTTP/1.1", upstream: "http://127.0.0.1:5000/submissions/qa/4?participant_id=&sample=&location=&quality_check-criterion=0&quality_check-condition=2&quarantine_status=", host: "apolloqa.demcloud.org", referrer: "https://apolloqa.demcloud.org/submissions/qa/4?participant_id=&sample=&location=&quality_check-criterion=&quality_check-condition=0&quarantine_status="

**Comment by blynchNDI** [comment]
@SarahCooperNDI and @johandrad just a heads up that I documented the QA error we found

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-16 12-14-05](https://user-images.githubusercontent.com/31080607/57869998-38ba0d00-77d4-11e9-8b20-38eb49c79d74.png)

Above is the image of the error produced (Carlos tried disabling all security on cloudflare and the error still occurred, so it appears to be an issue with the server not responding). 

Refreshing did not help, and repeating the steps produced the same error. All other pages and functionality of Apollo still worked though. Selecting VERIFIED AND REJECTED for the "Quality Check Condition" filter did not produce the same error, but OK, MISSING, and FLAGGED did produce it.

**Comment by cdoten** [comment]
We should probably have a test version that is NOT behind CF to avoid a
potential error point.

**Comment by blynchNDI** [comment]
Error is no longer present, and replicating a similar process also did not produce an error.
