### ISSUE TITLE
Location files not uploading

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#335]
On the qa test site, files that were previously uploading as location sets now no longer seem to be uploading. Two test files tried are attached. This is happening for both xlsx and csv, though it may be related to the bug fix to allow for uploading xlsx.

[Apollo Dummy Location Data (1).xlsx](https://github.com/nditech/apollo/files/3208345/Apollo.Dummy.Location.Data.1.xlsx)
[Tunisia.Locations (1).xlsx](https://github.com/nditech/apollo/files/3208346/Tunisia.Locations.1.xlsx)

**Comment by dodumosu** [comment]
@blynchNDI i assume that when you import the file, there's no error (a la #314), but no locations get imported?

**Comment by blynchNDI** [comment]
@dodumosu correct - I'm able to go through the three step in the pop-up box of uploading, mapping fields, and hitting confirm without any error showing up, but when I refresh the pages, there is still no location data present.

**Comment by blynchNDI** [comment]
Location sets are now uploading
