### ISSUE TITLE
How to enter location names in multiple languages

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#338]
This may simply be that I need instructions on how to do this, but I'm trying to figure out how to upload a location form with names in two or more languages. For example if I theoretically have location names in English and French (or English, French, and Arabic), how do I select all of them and map them to the correct fields? Currently, only the fields for Name (English) and Name (Arabic) are displaying for Apollo, so there is no entry for mapping to the french name.

@SarahCooperNDI I don't remember what we did to make the field for Name (Arabic) appear, so maybe you already know how to do this?

**Comment by dodumosu** [comment]
@blynchNDI in the deployment settings (admin), specify both the primary and other languages. You'll then be able to select columns with names in other languages

**Comment by blynchNDI** [comment]
Ah make sense, thanks Dipo!
