### ISSUE TITLE
Participant Upload Fields float outside of box

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#352]
The fields for uploading participants is now below the box where it should be, as seen in the screenshots attached. The buttons still seem to work.
![Screenshot from 2019-05-28 14-55-48](https://user-images.githubusercontent.com/31080607/58504684-2b4c3d80-8159-11e9-8ef8-57c8c90f2cb3.png)

![Screenshot from 2019-05-28 14-55-51](https://user-images.githubusercontent.com/31080607/58504651-1a9bc780-8159-11e9-9b16-097804d1d6ce.png)

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI This now also seems to be an issue with location uploads (see below)

![Location Upload Fields in Wrong Place](https://user-images.githubusercontent.com/48285413/59949582-882dd180-9441-11e9-8984-f707a6d88685.png)


![Location Upload Fields in Wrong Place 2](https://user-images.githubusercontent.com/48285413/59949692-de9b1000-9441-11e9-8459-84d05d53a908.png)

**Comment by takinbo** [comment]
It was but has been resolved in more recent updates.

**Comment by blynchNDI** [comment]
Issue is resolved
