### ISSUE TITLE
BUG FIX: Data summary on mobile generates a zong error

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#353]
Clicking on data summary from a mobile device (IOS 6) generates a zong error

**Comment by SarahCooperNDI** [comment]
Specifically under the event Test Event -- Data Summary is Ok on mobile for the Arabic Location Testing event.

**Comment by blynchNDI** [comment]
Looks like a repeat of #341

**Comment by takinbo** [comment]
Yes. Will be addressed in #341
