### ISSUE TITLE
BUG FIX: Error saving changes to Administrative Division parents

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#358]
I forgot to set Country as a parent to Governorate in the location set ARABIC ENCODED (screenshot below).  I repeatedly tried editing Governorate to set Country as a parent, clicked Update and then clicked Save.  Every time I refresh, it says "your changes have been saved" but the change has not actually saved (screenshot below).

![Admin Division Update Error](https://user-images.githubusercontent.com/48285413/58717100-730cd800-8398-11e9-8a4c-a2a7da976a15.png)

**Comment by blynchNDI** [comment]
(This is another case of #334 )

**Comment by takinbo** [comment]
Yes. Thanks @blynchNDI. Closing in favor of #334
