### ISSUE TITLE
Menu Standardization

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#359]
We have two different menu structures for what (in theory) seems that it should be the same menu in Apollo (see screenshots below). Can we standardize?  Personally I like the icons and would suggest migrating them over to the new font (so keep Menu Two but add icons from Menu One).  Thoughts? 

Menu One

![Menu Structure One](https://user-images.githubusercontent.com/48285413/58718543-bfa5e280-839b-11e9-809a-3c289b5e6af9.png)

Menu Two

![Menu Structure Two](https://user-images.githubusercontent.com/48285413/58718685-0e537c80-839c-11e9-93a9-ba324a29f4a7.png)

**Comment by stigsfoot** [comment]
@SarahCooperNDI would you be open to segmenting all UI work, nav included to a future Sprint/theme? 

Let me know if you're ok with that.

Context: The team is working on a design system that will apply reusable components to enable the non-designers amongst us to adapt best practices across all apps.

Tim, the recommendations are based on this design system (example nav). Though if you've never used a reusable.component or a design system, we'd need to talk it through. https://v1.clarity.design/navigation

**Comment by SarahCooperNDI** [comment]
@stigsfoot Sure! -- have removed this from 3.7

**Comment by takinbo** [comment]
Please note that UI modifications are being made incrementally and not all interfaces have been upgraded. This is intentional and is being worked on. Please use #177 to report on interface related issues. Closing this so we don't have a lot of issues tracking the same.
