### ISSUE TITLE
Zong error received for page 2 of checklist form

### ISSUE THREAD

**Issue by johandrad** [nditech/apollo#360]
In checklist forms, trying to navigate to page 2 of list gives a zong error message.

**Comment by blynchNDI** [comment]
This is for the event labeled "testing event". Also note that for the participant tab, only 13 participants appear, when there are 27 participants in the upload tab as well as when exporting the participant tab.

**Comment by johandrad** [comment]
It's happening in "Test" event, too

**Comment by blynchNDI** [comment]
All checklist pages are now loading
