### ISSUE TITLE
Dashboard pie chart color enhancement Part II

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#379]
Could the color for partial messages on the dashboard be changed from pink back to the yellow color we had in Apollo 2.x?

**Comment by takinbo** [comment]
We would revert the colour scheme due to the controversy around choice of colours for the slices.

**Comment by sarahmoulton** [comment]
Hi @takinbo could we keep the blue for complete? The purpose for the change was to address the red/green confusion for those with colorblindness. The pink color for partial was the only one we wanted to change - couldn't that be yellow?

**Comment by blynchNDI** [comment]
Right, so just to summarize feedback from the two Sarah's I think we want:
> Complete - Blue (new color)
> Partial - Yellow (old color)
> Missing - Red (new color/old color)
> No Signal - Grey (new color)

**Comment by takinbo** [comment]
The requested changes have been made. Please review and close this issue.

**Comment by blynchNDI** [comment]
We seem to have finally reached consensus approval of the color scheme
