### ISSUE TITLE
Drop "All Groups" from Participant Search Fields

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#380]
Richard and I are agreed that all functionality that used to be covered by "groups" is actually more effectively covered by "samples" so we don't see a need for groups going forward.  Would it be possible to drop the "All Groups" search field?

![All Groups Feature - Disable](https://user-images.githubusercontent.com/48285413/59953168-d1375300-944c-11e9-8a35-d7dd32579352.png)

**Comment by blynchNDI** [comment]
All groups filter is removed
