### ISSUE TITLE
Move "No Signal" Column to Immediately After ID

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#382]
Could we move the no signal column so it comes immediately after ID? We love the icons -- but think it will be easier for clerks to spot a "no signal" observer who should not be contacted if it's further left on the screen

![Move No Signal Column to After ID](https://user-images.githubusercontent.com/48285413/59953848-f5e0fa00-944f-11e9-9f9a-593561ec1d55.png)

**Comment by blynchNDI** [comment]
Icon is moved to after ID
