### ISSUE TITLE
restore ability to quarantine checklists

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#387]
The checklist edit interface is missing the ability to quarantine records.

Please see #188

**Comment by blynchNDI** [comment]
Quarantine feature is there, but it doesn't seem to actually be working or doing anything. Also note #432 , where we're looking to make quarantine available for individual participants with multi-participant locations

**Comment by takinbo** [comment]
#432 will be addressed. The quarantine feature works only for data summaries and was tested. Do help do some testing and report any bugs found, if not. This issue should be closed.

**Comment by blynchNDI** [comment]
Ok, I couldn't remember if the quarantine status previously affected the dashboard / pie charts as well - @SarahCooperNDI ?. If not, this can be closed.

**Comment by blynchNDI** [comment]
Just talked with Sarah, and so will close for the moment, and reopen if it is determined that we do want quarantined data to be removed from the dashboard.
