### ISSUE TITLE
Make Event Name Easier to Identify in New Menu Structure

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#389]
The name of the event is currently fainter than the names of the different menu options in Apollo.  Could we make it easier to identify the event name by including the text "Event:" in front of the name and making all text bolder and/or darker so that it is easier to read? (See screenshot below)

![Event Name Easier to Identify on Menu](https://user-images.githubusercontent.com/48285413/60359680-bbbfad00-99a7-11e9-98de-00801b6d9f8c.png)

**Comment by SarahCooperNDI** [comment]
@blynchNDI Looks to me like this has been fixed?  Should we close this issue?

**Comment by blynchNDI** [comment]
Looks like this has indeed been resolved

![Screenshot from 2019-07-24 10-23-09](https://user-images.githubusercontent.com/31080607/61801591-0d1f5880-adfd-11e9-870e-3820e6fb38ca.png)
