### ISSUE TITLE
Include Menu Icons from Old Menu Structure in New Menu Structure

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#390]
We liked the icons that were included in the old menu structure (home icon for dashboard, checklist icon for checklists, person icon for participants, etc.)  Could these icons be migrated into the new menu structure? The one change we would suggest is that currently checklist and critical incidents have the same icon.  Could we instead use an exclamation mark for the critical incidents?

**Comment by takinbo** [comment]
@SarahCooperNDI while this will be a nice-to-have feature, it doesn't improve functionality or the user experience so marking this as `wontfix`.
