### ISSUE TITLE
Changes to critical incident forms are only partially reflected in the data summary page

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#394]
When a critical incident form is changed mid-event and a new question is added, the critical incident checklist management page updates to reflect the new questions. However on the data summary page, the summary section updates to reflect the new question, but the detail section does not include the new question

**Comment by dodumosu** [comment]
This is related to the fact that newly created questions have a default Not Applicable analysis type. Setting that when creating the questions will resolve this.
