### ISSUE TITLE
Filtering by form field for Critical Incidents produces 502 error

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#395]
Likely same or similar issue as with #323 . When filtering a Critical Incident form by the responses to a question, a 502 error is produced. (This has been replicated on sites not affected by the ci/cd pipeline.) The error produced in the logs includes: 'jinja2.exceptions.TemplateNotFound: f405.html' . From what I remember when fixing #323, this may have been related to an issue with the method being used and POST vs GET

**Comment by dodumosu** [comment]
@blynchNDI could you provide a screenshot of the incident list _before_ you hit the filter button?

**Comment by blynchNDI** [comment]
Let me know if this is sufficient detail below. I'm working on setting up the QA site and recreating it there. 

![critical_incident_error](https://user-images.githubusercontent.com/31080607/60817477-c0375300-a169-11e9-9cee-e8537eaccbc8.jpg)

**Comment by blynchNDI** [comment]
Filtering is working
