### ISSUE TITLE
Questions with multiple answer does not display correctly on the edit checklist page for critical incidents

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#396]
When the question type that allows you to select multiple answers is added to a critical incident form, the choices overflow on the edit checklist page for the critical incident form as seen in the attached screenshot
![Screenshot from 2019-07-05 14-44-35](https://user-images.githubusercontent.com/31080607/60740446-c17f3a80-9f33-11e9-89e9-08bed0100d44.png)

**Comment by blynchNDI** [comment]
Display is fixed

![Screenshot from 2019-07-16 13-35-09](https://user-images.githubusercontent.com/31080607/61316254-94057d00-a7ce-11e9-903c-89e0866730c0.png)

**Comment by blynchNDI** [comment]
Debated reopening this vs creating a new issue - the original issue was fixed for the edit critical incident page, but the same bug is happening on the "Add Checklist" when you try to manually submit a critical incident, as seen below. Hopefully the same formatting fix can just be copied to this page as well

![Screenshot from 2019-07-30 12-04-18](https://user-images.githubusercontent.com/31080607/62146003-76521080-b2c2-11e9-9644-0c306eb16a76.png)

**Comment by takinbo** [comment]
Resolved #451
