### ISSUE TITLE
Rejected Critical Incident should not appear in the data summary

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#398]
Currently, if a critical incident is marked as rejected, it still appears in the data summary. Let me know if there is a reason why this would be desirable, but presumably rejected submissions should be excluded from the data summary page.

**Comment by dodumosu** [comment]
there's a filter on the incidents page to restrict the data summary to each status for an incident report. defaulting to excluding rejected incidents would break the (established) workflow. @SarahCooperNDI care to weigh in?

**Comment by blynchNDI** [comment]
Confirmed that we don't want to remove this functionality. Will open a new ticket to address default filter for critical incidents
