### ISSUE TITLE
Checklist and data summary not updating with data

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#412]
Editing the checklists and inputting data does not seem to update the data summary or the dashboard on the qa site.

**Comment by blynchNDI** [comment]
Upon further testing, the issue seems to be that submitted data is appearing in the participant column but not automatically populating the location column on the edit checklist page. (When data is manually put into the location column, the dashboard and data summary update)

**Comment by dodumosu** [comment]
Data summaries and the dashboard use location checklists as their data source.

**Comment by blynchNDI** [comment]
Error is fixed
