### ISSUE TITLE
App-based submissions not appearing

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#413]
There seems to be an issue in which app-based submissions are not always recorded. It's unclear if I'm precisely pinning down the bug, but it appears to be an issue in which if data was submitted from another source previously that was not app-based submission, the app-based submission does not overwrite this data. (Instead, app-based submission only seems to overwrite other app-based submission data)

**Comment by blynchNDI** [comment]
Try fixing #412 first, as that could potentially be causing this issue as well

**Comment by blynchNDI** [comment]
@dodumosu - Haven't done extensive testing, but app-based submissions don't seem to be showing up anymore

**Comment by takinbo** [comment]
A bug fix was applied. Please test and report back.

**Comment by blynchNDI** [comment]
Bug fix appears to be working well - I'm not seeing any problems
