### ISSUE TITLE
Specify an event when creating checklist

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#415]
Currently, when creating checklist, it is created for whichever event the user is currently in. However given that the form menu is part of the admin menu and that all forms appear regardless of which event you are in, it might be better to add an additional dropdown menu at the top of the popup create checklist window (above the dropdown menus for form, role, and location type) so that the user doesn't have to remember what event they're in, and so they can easily create forms for other events. There may be technical reasons however for why this would be difficult to do, in which case this can be scrapped.

**Comment by takinbo** [comment]
Fixed in #453

**Comment by blynchNDI** [comment]
This is great. Looks good - you can now create a checklist for any events regardless of what event you're in.
