### ISSUE TITLE
Provide warning when navigating away from a partially created admin menu page

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#416]
Relating to the feature in #180 , it would be desirable to have the same warning feature be applied to the admin menu sections (location, participant, forms, events, roles, users, etc.) when navigating away from a page with information filled in that hasn't been saved

**Comment by takinbo** [comment]
Adding this feature to checklists was a major need considering the amount of data a data clerk might have filled in only to navigate away without saving. Seeing that data input is minimal on the other data input pages you've mentioned, I wouldn't consider this high priority.
