### ISSUE TITLE
Minor UI - Labels overlap when they are for small slivers of the pie chart

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#417]
The numbers labeling the percentage of the pie chart overlap when they are small numbers as seen below. Not terribly important however, and an obvious way to always avoid this from happening seems difficult.

**Comment by takinbo** [comment]
@blynchNDI there seems to be a missing screenshot.

**Comment by blynchNDI** [comment]
Again, this should be a very low priority item as the issue only appears for percents less than 5%

![Screenshot from 2019-07-17 10-40-15](https://user-images.githubusercontent.com/31080607/61384785-485edc00-a87f-11e9-8deb-080c07e3fa97.png)

**Comment by takinbo** [comment]
This seems to affect pie slices that are very small and to fix this, we hide the label if the pie slice is 3% or below. Fixed in #453
