### ISSUE TITLE
Message exports have BOM characters at the beginning of each column

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#43]
![code_2018-07-30_10-35-29](https://user-images.githubusercontent.com/1408662/43389711-4baabf56-93e4-11e8-9418-8a844a621bda.png)
See above image for example

Aha! Link: https://nditech.aha.io/features/APOLLO-202

**Comment by takinbo** [comment]
@dodumosu bump

**Comment by dodumosu** [comment]
![1_____virtualenvs_apollo2_bin_python_manage_py_shell__python2_7_](https://user-images.githubusercontent.com/1408662/59552157-2a9a1080-8f7b-11e9-9422-9a14f3db6704.png)
seems fixed in latest `HEAD` for the `version2` branch
