### ISSUE TITLE
Allow for quarantine individual participants at the same location

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#432]
Based on talking with @SarahCooperNDI :

Currently when you have multiple participants for one location, you can only quarantine the entire location, but not the individual participants. This would be useful, for example if one observer ended up at the right location but another didn't.

In addition, ideally the quarantine dropdown for location would stay in place, which would allow quarantine all observers for that location.

**Comment by blynchNDI** [comment]
Hitting Save with these settings for quarantine led to a zong error (hopefully Sentry gave you a notification)

![Screenshot from 2019-07-23 10-08-58](https://user-images.githubusercontent.com/31080607/61718968-0081fe00-ad32-11e9-94ea-5252b221f2d8.png)

**Comment by takinbo** [comment]
@blynchNDI I was unable to replicate this error and it doesn't appear sentry is configured so no exception was reported. Might want to look into the sentry setting.

**Comment by blynchNDI** [comment]
@dodumosu not sure with the configuration if were you able to see anything captured in sentry? Otherwise, it doesn't seem to be happening anymore for me either, so will close it if I can't replicate it in the near future

**Comment by blynchNDI** [comment]
This seems to be working very well and as expected. When you quarantine a location, that location drops out of the data summary and is not counted (so if there are 100 locations overall, the data summary drops to 99 locations total). If you only quarantine the observer, the observer information is not counted, and the location column goes blank where it was populated with observer data, but the location is not removed from the data summary (e.g it would still list 100 as the total); it is then up to a user to input data for the location, which then feeds into data summary
