### ISSUE TITLE
Clicking through layers on pie charts does not seem to be working

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#433]
When clicking through pie charts on the dashboard, rather than going to a breakdown by location hierarchy, it goes to a empty screen, which should not be happening unless this feature is currently under construction

**Comment by takinbo** [comment]
@blynchNDI could you attach a screenshot illustrating this behaviour?

**Comment by blynchNDI** [comment]
Closing because I cannot reproduce it at all. Will reopen if I find a consistent way to reproduce it
