### ISSUE TITLE
Change Text of "Has Registered Voters" Tick Box Under Administrative Divisions

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#436]
My understanding is that this box needs to be ticked any time we expect **any** location based control data -- including not only registered voters but also things like ballot box codes or polling station codes that we might use to confirm that observers are in the right place.  If this is correct, could we please change this text to "Has location-based control data" so that it is clear that this needs to be ticked even if the control data we expect is something other than RV?

![Has RV in Admin Divisions](https://user-images.githubusercontent.com/48285413/61545151-caccd480-aa14-11e9-88dd-1a7ed39f7fd0.png)

**Comment by dodumosu** [comment]
actually, the check is specifically for registered voters. other control data can be stored in extra data attributes. the only thing this affects is adding a specific column for uploads and creating a specific column in exports.

**Comment by SarahCooperNDI** [comment]
Per our call @blynchNDI this can be closed out.  Thanks all!  :-)
