### ISSUE TITLE
Edit submission view does not load comments

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#44]
Comments are not saved with a deployment, so when the submission edit view is loaded, the associated comments are not.

Possible fixes:
- set deployment on saving comments;
- instead of loading submission comments through their service, load directly from the submission object (i.e: use `submission.comments` instead of `services.submission_comments.find(submission=submission)`

Aha! Link: https://nditech.aha.io/features/APOLLO-201

**Comment by takinbo** [comment]
@dodumosu bump
