### ISSUE TITLE
Make "Confirmed" the default filter for Critical Incidents data summary page

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#441]
Currently, the default filter option for the critical incident data summary page includes all reports, with options for filtering to just include any of the 4 types of report summaries. The requested change is to make Confirmed to be the default filter, with the option to filter by any of the other 3 report types, as well as to filter by the current default option in which all reports are displayed, which should be called "All".

So, the options should be:
-Confirmed (*default option*)
-Unmarked
-Rejected
-Citizen Report
-All

**Comment by blynchNDI** [comment]
Looks good. Only additional feature requests would be:

1. On the dropdown menu on the critical incident data summary page, renaming 'Status' to 'All'

2. @SarahCooperNDI can weigh in, but I believe while we want the data summary page to be filtered by confirmed, we do not want the critical incident 'checklist' page to be filtered by confirmed by default, and it should instead by default display all submissions (the idea being the checklist page allows for processing all submissions, and the data summary page displays only the one that are confirmed by default)

**Comment by takinbo** [comment]
We should probably leave it under review.

**Comment by blynchNDI** [comment]
Per conversation today:
-critical incident form/checklist page should have no filter by default (rather than confirmed)
-The filter for the data summary page should be kept the same (defaulting to confirmed), but the filter for all entries should be called 'All' rather than 'Status'

**Comment by takinbo** [comment]
Resolved in #451

**Comment by blynchNDI** [comment]
The edit checklist filter was fixed so that All Incidents is the default filter there. However this change also applied to the data summary page, where the default filter was requested to be Confirmed Incidents. Not sure however how critical this is.

**Comment by takinbo** [comment]
A patch was merged that corrects this behaviour. Confirmed incidents are now the default for the incidents data summary.

**Comment by blynchNDI** [comment]
The patch seems good - the correct default filter is in place for both pages
