### ISSUE TITLE
Make it more difficult to delete events, participant sets, location sets, etc.

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#452]
Currently, there is a two click process to delete events/participant sets/location sets, but it is still somewhat easy to mindlessly click through it. We should discuss an exact fix, but something more alarming to stop you from deleting something on election day would be good. Possibly can pull on the Apollo 2 warning here ...maybe even make it 3 clicks?

**Comment by takinbo** [comment]
I doubt that it would make any difference considering the fact that there's a confirmation warning just before a deletion occurs. I don't think it's worth the extra work to implement something different. Marking as wontfix.
