### ISSUE TITLE
Location Data column not updating based on Observer column

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#463]
On the apollo qa site in the test event, updating the observer data column does not update the location column. Since it is a one observer model, changes to the observer column should automatically update the location column. This appears to happen whether the data is edited on the edit checklist page, or sent in as an sms message.

**Comment by takinbo** [comment]
Apollo allows the data clerk to override whatever the observer sent. If the location data is modified, then it overrides and will continue to override whatever the observer sends. Closing this issue for now. If this is not the case and you think it's really a bug, please re-open.
