### ISSUE TITLE
Change log not displaying all changes

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#464]
There are issues in which the change log is not matching the actual data. For example on the apollo qa site, observer 41041 (*url*/submission/79) has three data points filled under the observer column, none in the location column (related to #463 ), but the change log indicates there should be eight points of data. Don't remember what was actually done for this entry, but this would indicate that something with the change log is not working correctly

**Comment by takinbo** [comment]
From my observation, the changelog shows that eight data points were initially added to the checklist, the second operation shows that, five were deleted, four added and one changed. If you inspect the changelog, it is apparent that the changes match with the current state of what's there currently.

Green badges represent new data, red means deleted and yellow means changed. Closing.
