### ISSUE TITLE
Changes made to observer column and location column cannot be saved at once

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#468]
If on the edit checklist page a change is made to the observer column, and then the location column is selected and a change is made there, both changes will not be saved. Rather only the changes made in the column currently selected at the time of clicking the save button will be saved. Presumably, there would be use cases in which a data clerk might be editing two columns at once and want to save each (or if perhaps this is not a workflow that should be allowed, then there should be a warning/alert when switching columns about how data in the previous column will not be saved)

**Comment by takinbo** [comment]
This is not a bug but a training issue. When a data clerk switches from an observer to a location, the observer column gets disabled. The indication should be such that data for the disabled column will not be regarded. Marking as `wontfix`.

**Comment by blynchNDI** [comment]
Agreed as a won't fix
