### ISSUE TITLE
Remove 'Mark As True if Present' for text questions?

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#472]
#442 specified that 'Mark As True if Present' should be removed for numeric questions. Opening this, as I'm not sure whether it should also be removed for text questions as well - @SarahCooperNDI ?

**Comment by takinbo** [comment]
`Mark as true if present` is a legacy feature for critical incidents that is no longer used in Apollo.

**Comment by blynchNDI** [comment]
The feature is removed
