### ISSUE TITLE
Change 'Track Data Conflicts?' to 'Don't Track Data Conflicts'

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#481]
Because in most cases data conflicts will be track (and the location column should be used), it would be preferable to switch the default so that Data Conflicts are tracked. Therefore, instead of clicking a checkbox labeled `Track Data Conflicts?` to turn on tracking on, instead have a check box labeled 'Don't Track Data Conflicts' that when clicked would turn off tracking data conflicts

**Comment by takinbo** [comment]
#517 implements this feature.

**Comment by blynchNDI** [comment]
Data conflict is flipped so that is now on by default, and a 'Don't Track Data Conflict' box must be clicked to turn it off
