### ISSUE TITLE
On pages where location levels appear as columns, the columns should be arranged in according to their order in the hierarchy

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#485]
Currently, if the admin divisions used are Country, Region, Subregion, and Polling Station, these four columns will appear on pages such as the checklist page in order from highest level to lowest level. However if changes are made to the admin divisions, sometimes the order of these columns will get out of order and no longer be ordered from highest to lowest. For example the QA site's test event checklist is currently ordered Country, Subregion, Polling Station, Region. Just to guess at a solution here, we may want to hardcode the columns to display according to the order in which they have parents - however this might be a little trickier to account for edge cases in which there is not a linear hierarchy.

**Comment by blynchNDI** [comment]
Also note that this sometimes also occurs on the create checklist page as well.

(Also, a screenshot of the this occurring for columns in case this is useful):

![Screenshot from 2019-08-16 12-50-17](https://user-images.githubusercontent.com/31080607/63184024-73765000-c024-11e9-83b8-9215f8d82f09.png)

**Comment by takinbo** [comment]
Resolved in #498

**Comment by blynchNDI** [comment]
Hard to replicate this and prove this is fixed in all cases, but at the very least, it is not happening in the cases it was occurring before. Will close, and reopen if it is found to be occurring
