### ISSUE TITLE
Inability to upload registered voters or extra fields

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#491]
Copying this into github from the email sent. These issues need to be fixed in order for properly setting up the WTV site. Errors were encountered with uploading the spreadsheet below. Upload was entirely successful when just the 5 location names and codes were uploaded (columns B through K). However when register voters was checked for PU on the admin division page, trying to upload column Q as 'PU registered voters' did not work right; the upload menu completed with no error, but only 3 locations uploaded out of 487 (see /admin/locationset/locations/23 on the qa site).

Independently, there was also an error with this upload sheet when trying to use additional fields. Trying to upload columns U, V, and W as three different extra fields linked with the LGA, Ward, and PU levels respectively led to a similar outcome, where the upload succeeded and did not produce an error, but only one location uploaded. ( /admin/locationset/locations/22 on the qa site).

[Kogi Locations 20190814 RLK (1).xlsx](https://github.com/nditech/apollo/files/3510240/Kogi.Locations.20190814.RLK.1.xlsx)

**Comment by takinbo** [comment]
Resolved in #498

**Comment by blynchNDI** [comment]
Successfully uploaded the file using extra fields and registered voters
