### ISSUE TITLE
Allow default participant fields to be hidden

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#504]
Create the ability to choose whether each default participant field is visible (similar to how you can make extra fields visible or not)  - presumably this would be done on the edit participant set page.

**Comment by takinbo** [comment]
#512 adds support for this. Display of the role, gender and organization columns are now optional.

**Comment by blynchNDI** [comment]
Looks good. The only things you can't hide are location, name, phone number, and participant ID, which seem like things you would want to keep
