### ISSUE TITLE
Aggregated Data Export is sometimes blank

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#505]
This is an issue that appears to occur sometimes but not with a clear cause. On the WTV site, three of the four events do not have this issue, while "KB Refresher Training - Recruitment" does. Not sure how easy it is to pin down a cause of this. Let me know if you need credentials for frontend access to the website.

**Comment by takinbo** [comment]
Yes, if you could create credentials and send via email, we can observe and identify the problem.

**Comment by blynchNDI** [comment]
Aggregated exports are working on new sites, and for the QA site for events/checklists where it wasn't previously working. It appears the issue is fully resolved
