### ISSUE TITLE
For Categorical Analysis, expected value defaults to 0 rather than null

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#521]
If the expected value is left blank for the categorical analysis, after exiting the form builder and returning to it, the value defaults to 0. If it is left blank, it should default to null in order to allow the full histogram display

**Comment by takinbo** [comment]
#530 implements a fix for this. Now you need to explicitly set the analysis type for numeric questions to `histogram` to get this behaviour.

**Comment by blynchNDI** [comment]
Histogram feature is working exactly as intended
