### ISSUE TITLE
Changing Participant Name causes error

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#528]
Revising this based on more testing (the issue does not seem to actually be related to Amharic). Changing the name of a participant seems to cause significant errors. For example changing the name to O led to most of the participants disappearing. However clicking on the column headings to change sorting sometimes changes the number of observers that are displayed.

See QA site at `/admin/participantset/participants/1`, or `/admin/participantset/participants/20`

**Comment by takinbo** [comment]
I was able to replicate the issue by:

1. Set a primary language and add an alternative language to the deployment
2. Go to the participants index page and sort by Name. Both ascending and descending sorting yield different results.

**Comment by blynchNDI** [comment]
@takinbo and @dodumosu - Thanks Tim for figuring how to replicate this. On my end, the steps you described still replicate the bug - I tried spinning up a fresh instance, and was still able to replicate the bug there as well

**Comment by blynchNDI** [comment]
Just for further narrowing in, it looks like even just saving a couple participant entries without evening changing any information replicates the bug

**Comment by takinbo** [comment]
fixed in #550

**Comment by blynchNDI** [comment]
Appears fixed. Can't replicate it with any variation of what was causing it before
