### ISSUE TITLE
Total on dashboard for Arabic not displaying correctly

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#529]
When language is switched to Arabic, the total number on the dashboard is partially cutoff as seen below

![Screenshot from 2019-09-06 15-44-44](https://user-images.githubusercontent.com/31080607/64456076-541b9180-d0bd-11e9-8d72-1559ae6aab54.png)

![Screenshot from 2019-09-06 15-38-18](https://user-images.githubusercontent.com/31080607/64455822-9c867f80-d0bc-11e9-8d62-278697aa638e.png)

**Comment by takinbo** [comment]
There's little reason why this should be the way it is. I suspect a caching issue. Could you turn off caching from CloudFlare or at least flush the cache?

**Comment by blynchNDI** [comment]
I tried cache clearing, and it appears to be occurring on a new site as well. The math itself however seems fine - I believe it's just a minor formatting issue, where there is an extra space that is cutting off the beginning of the Total number

**Comment by takinbo** [comment]
I'm unable to reproduce this. I'm still going to go out on a limb that it is due to some assets being cached in the browser or on cloudflare. Try a different browser?

![screenshot-1568837421](https://user-images.githubusercontent.com/41004/65182254-7237a900-da50-11e9-9420-2967182fc782.png)

**Comment by takinbo** [comment]
Same for the pie charts

![screenshot-1568837490](https://user-images.githubusercontent.com/41004/65182290-88456980-da50-11e9-9ad5-634897acb61f.png)

**Comment by blynchNDI** [comment]
@takinbo i just did some testing and it appears this only happens when the total is 3 digits or more (although it doesn't have a problem if other fields are 3 digits). See if it replicates on your side with 3 digits, or else I'll continue looking into it on my side

**Comment by blynchNDI** [comment]
Indentation is fixed
