### ISSUE TITLE
Exporting participant sets on QA site gives wrong data

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#535]
Currently, hitting export for any participant set on the QA site gives the wrong export - rather than giving the participants for that set, it seems to always export an identical set of participants that stretches across several different participant sets. I'm guessing this a weird offshoot of #528 , but I wanted to flag it in case fixing issue 528 doesn't fix this

**Comment by takinbo** [comment]
It does appear it might be related to #528 like you mentioned. We'll be investigating it and releasing a patch as soon as possible.

**Comment by blynchNDI** [comment]
This issue appears fixed - no issues remain with getting the wrong export.
