### ISSUE TITLE
Field Coordinator should have read-only access to checklists for the participants in their assigned region

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#540]
Currently, field coordinators can see the dashboard pie chart for their region. Per the call with Tim, they should also have read-only access to see the checklist entries for participants in their region. Given that there the only current permissions for checklists seems to involve editing or submitting forms rather than just read-only, it may be useful to add a permission for read-only access such as "View Checklists" or "View Forms"

**Comment by takinbo** [comment]
If the field-coordinator role is created *after* the forms are in the system (this is only likely to happen in a system that is upgraded prior to when the feature was added) then you would need to add those forms as resources to the role. On new instances, you don't have to explicitly do this as it is done implicitly.

![screenshot-1568836615](https://user-images.githubusercontent.com/41004/65181427-88dd0080-da4e-11e9-8395-d4e183e2f262.png)
