### ISSUE TITLE
Mapping gender for multiple values

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#546]
When uploading participants and mapping the gender, only `f` or `m` seems to work. Ideally, `F`, `Female`, and `female` should also map to female in the system, particularly since export a participant set comes out with `female` or `male` under gender

**Comment by takinbo** [comment]
Exports will now contain the code for the gender (M for male and F for female) and will accept either the code or the full word for the gender. It allows the full word because it uses the first character as the gender code.

**Comment by blynchNDI** [comment]
Great solution. Anything starting with m/f works
