### ISSUE TITLE
Rename "Save" to "Save and Exit"

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#548]
For the creation/editing page for Location Sets, Participant Sets, and Events, "Save and Continue Editing" and "Save and add Another" do what is described, while "Save" saves and exits - thus Richard's suggestion is to rename it as such

**Comment by takinbo** [comment]
These are defaults that we extended and do exactly as they suggest. We are happy to remove "Save and Continue Editing" and "Save and add another" if this is causing confusion.

**Comment by blynchNDI** [comment]
I personally haven't had an issue with it myself. Let me do some informal user testing and see if this is actually causing any problems for users

**Comment by blynchNDI** [comment]
Will close for now, and reopen if this is raised as an issue again
