### ISSUE TITLE
Adding button on location/participant page for back/close/exit?

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#549]
Richard has request a 'back button' that would for example move from editing a specific participant set back to the participant set "landing page". This would be for the participant set page, location data upload page, and the administrative division page.

**Comment by takinbo** [comment]
The topmost item on the breadcrumbs navigates back to the participants set. The same applies for locations and admin divisions.

![screenshot-1568838435](https://user-images.githubusercontent.com/41004/65183330-c93e7d80-da52-11e9-99fe-bba0c0991a53.png)

**Comment by blynchNDI** [comment]
Yeah, this makes sense to me
