### ISSUE TITLE
Top level admin division doesn't upload

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#552]
This was originally found by Richard for the Nigeria site, and reproduced by me testing out Malawi data. I'll send the location admin divisions and location upload by email. Uploading the latter seems to upload 2071 out of 2072 locations, but the top level admin division, Country `1`, doesn't seem to be uploading. Exporting the upload does have the Country level there - it's just not an individual item. Reporting it since it's not in line with how Apollo normally works, but I'm not sure it actually affects anything negatively.

**Comment by takinbo** [comment]
@blynchNDI I don't believe you've sent the offending files.

**Comment by blynchNDI** [comment]
@takinbo I had sent by email a little while ago but it probably got lost in the shuffle around the Tunisia elections. Just resent the files

**Comment by dodumosu** [comment]
@blynchNDI has this repeated since the order of admin divisions was fixed? please verify as i have not been able to reproduce
