### ISSUE TITLE
Validation errors when editing a participant without a supervisor results in an error

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#562]
If the user goes to the participant page and changes an observer's role to the blank field on the pulldown menu, it gives a zong error. Marking this as minor, as presumably you would almost never need to make a user's role change to nothing.

**Comment by dodumosu** [comment]
was unable to reproduce. see attached screenshot for relevant error message.

![Participants_·_Edit_Participant_·_400011_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/66829377-21ca4300-ef4b-11e9-9721-fa387372cdd7.png)

**Comment by blynchNDI** [comment]
Interesting - I'm not getting the error message you are, and instead I always get the zong error under seemingly any permutation. I can try seeing if it's different with a fresh version of Apollo as opposed to one that I've been updating from previous versions.

**Comment by dodumosu** [comment]
after further testing, the server side error (the "Zong") is raised if and only if the participant does not have a supervisor set. so the issue is not so much with the role, but the supervisor.

**Comment by blynchNDI** [comment]
Ah nice catch. #581 seems to have fixed this
