### ISSUE TITLE
Issues with location imports and incorrect exports

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#566]
I've tried and failed to figure out exact steps for replicating these, but all have appeared on the qa site. This seems to have occurred near when #563 happened, so perhaps it's related to that or #552. I've grouped them together as I suspect at least 2 if not all 3 are related. The issues are as follows:
- For location set Issue566A, the export of administrative divisions is blank, despite an administrative division hierarchy existing and working (/admin/locationset/builder/87)
- For location set Issue566B, the import captured all locations based on the export, but does not seem to be displaying 3 of them. In addition, the export is missing all locations at the polling station level (while all 100 of them appear within Apollo). (/admin/locationset/locations/94)
- For location set Issue566C, only the lowest level locations appear in Apollo (100 out of the 126 that should appear when higher levels of the administrative division are accounted for). The export however contains the missing 26 higher level locations, though the higher level locations do not have separate lines the way they are for a normal export (e.g. the country location normally has a row to itself, in addition to being the start of other rows as well) (/admin/locationset/locations/84)
- Location set Issue566D also seems to be displaying a similar issue to Issue566B (admin/locationset/locations/33)

**Comment by dodumosu** [comment]
@blynchNDI on importing the original data set that you used, can these issues be replicated?

**Comment by blynchNDI** [comment]
@dodumosu I'm reviewing this now. The issue for 566A is no longer occurring, and it looks a lot like 566B, 566C, and 566D were likely due to issues that have since been fixed as part of #547 and #485 where location levels were getting scrambled. As such will close
