### ISSUE TITLE
user should be able to create a survey form

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#574]
* Survey forms will support having a form identification number that acts as a unique identifier and appears as a new column on the survey list.
* The form identification number is uploaded by the user when creating the empty survey submissions in the database
* Survey forms will make a mandatory first question asking for the form identification number

**Comment by takinbo** [comment]
![screenshot-1571056947](https://user-images.githubusercontent.com/41004/66752115-3392e400-ee80-11e9-94f5-5b69d1d2f4eb.png)

@blynchNDI what are your thoughts? The idea is to have the admin upload a file with three columns: one with the participant id, the second with the form serial number and the last with the date of expected submission.

**Comment by takinbo** [comment]
![screenshot-1571057258](https://user-images.githubusercontent.com/41004/66752397-d5b2cc00-ee80-11e9-9cdd-0e6849bee291.png)

Better help alternative.

**Comment by blynchNDI** [comment]
@takinbo This looks good to me. I know for normal checklist creation, you specify the location hierarchy level and the role as well, but I'm not sure if those are still necessary? Given that you will presumably be specifying in your upload exactly which participants are being uploaded, the observer type is no longer crucial. I've not played around much with setting different location levels for creation beyond the bottom most one, so I'll defer to you as to whether it still provides value for this.

If you are looking to implement expected day of submission, I'd just make sure to leave it as an optional field, as it likely won't be used for all cases. (For example the day-by-day breakdown should still be able to populate with the actual number of responses received each day, without a certain target or certain submissions being expected for that day). Let me know if that conflicts with any way you were planning on implementing it.

**Comment by blynchNDI** [comment]
Also @takinbo , I think this is the only issue we need done for tomorrow - the others are less urgent

**Comment by takinbo** [comment]
I doubt we've had a number of cases where specifying a different administrative division than where the participant is has been the case. We would see if it is necessary to add that again. Meanwhile, you are right that we would determine the location just by looking that up from the pariticpant specified in the upload.

The daily targets are determined from the expected submission dates for the form serial numbers that are uploaded. Without that, we would have a chart with just one bar with all the submissions expected on the same day. In such a situation, it would be possible to turn off the daily chart as it would not make any sense.

**Comment by blynchNDI** [comment]
One other thing I remembered - we didn't explicitly state in the SOW how the survey form would work for mobile submissions. I believe you had mentioned something along the lines of mobile submissions starting with "FORM_PREFIX|PARTICIPANT_ID|"X"|FORM_NUMBER", so something like XA43X22 for participant ID 43 submitting form XA with form number 22. Let me know if that works for you. For full functionality it's probability good for all forms to be submit-able over both mobile and app, but with our current use-case we only care about apps for the moment, so mobile submission ability is a much lower priority if it will require some significant code changes

**Comment by blynchNDI** [comment]
Ok, sounds good with regards to role and administrative division level.

With regards to the expected submission dates, I believe Marko actually wants the displays to reflect the actual submission date rather than when the observer was supposed to submit it. For example if the observer is supposed to submit 40 submissions each on Day 1 and Day 2, but submits 35 on Day 1 and 45 on Day 2, it would be important to see this, so as to know whether observers are maintaining pace, or are regularly missing targets and having to make it up the next day.

**Comment by blynchNDI** [comment]
Survey form can be successfully created and seems to work well. Will log any bugs that come up as separate tickets
