### ISSUE TITLE
form type should determine what form options are displayed

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#575]
When editing form options for a given form, the available options should reflect what form type is being worked on.

If a form type that is not a checklist is being edited, the form options specific to checklists shouldn't be displayed. These include: Accredited Voters Field, Blank Votes Field and Invalid Votes Field.

**Comment by blynchNDI** [comment]
@takinbo would it be possible to leave Quality Assurance as an option for critical incidents? I think you're right that it would never be applicable for a traditional election use-case, but I could imagine the tech team trying a new use case in which it would be useful. Not worth going to a lot of trouble over, but if it can easily be reinstated, it increases flexibility

**Comment by blynchNDI** [comment]
Ah ok, not worth it if it doesn't already exist
