### ISSUE TITLE
survey dashboard

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#578]
The survey dashboard will sport the completion status of all the submissions in the event; in addition, it will also (optionally and disabled by default) display a bar chart of the completion by day with each column showing stacked values of the completion status of each day in the event.

The bar chart should be navigable to show the breakdown by location.

**Comment by blynchNDI** [comment]
Just wanted to weigh in on this while it's still in progress - based off of what form options appear when you select a certain form type, it seems that the day-by-day breakdown is only designated for survey forms. This makes sense for the previous model where you would need to specify the expected submission date upon Survey Creation, but if we're moving to just recording the day something is submitted, I believe this feature should be possible for all three form types per the SOW, and would be desirable for all as well (Richard expressed a desire to use this for long-term observation)

**Comment by blynchNDI** [comment]
@takinbo just wanted to follow up to make sure this is good to be done for when the SOW finishes on Thursday. It sounded like though from our conversations that you're on track

**Comment by blynchNDI** [comment]
@takinbo Could you provide instructions on how to use this? I've turned on the feature on the form properties page and sent in submissions but I'm not seeing any display as of now

**Comment by takinbo** [comment]
The only thing you need to do is turn it on. The daily progress chart will start to populate once data starts coming in. Updates from the data clerk do not count; it has to be from the observer - either as an ODK or SMS update.
