### ISSUE TITLE
add extra data fields for quality assurance checks

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#580]
The participant id and the form id number are two fields that should be added to the quality assurance computation engine to allow for data comparisons. These will be treated as strings.

**Comment by blynchNDI** [comment]
@takinbo it actually does seem to treat them as numbers when doing numeric operations, and strings when doing concatenations, which is presumably the best of both worlds. Per your email, is this an intentional addition? Everything seems to work well

**Comment by blynchNDI** [comment]
Just saw the comment for concatenation - I assume then that they are stored as numeric values until concatenation is applied, which would be the ideal

**Comment by takinbo** [comment]
Correct. Values are stored as numeric and only converted to their string versions before concatenation.
