### ISSUE TITLE
Issues caused by two sections having the same name

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#585]
In the form builder, if you label two sections as having the same name, it causes issues on the checklist page. For example filters apply to both sections, and the completion/partial and pie charts displays do not seem to update correctly. This is definitely an edge case since naming two sections the same things defeats the purposes of giving them names to distinguish them (It's only occurred for me when I'm quickly building a form for testing and forget to change the names). Still worth looking into whether there's an easy fix for this, just in case a user accidentally does do this.

**Comment by takinbo** [comment]
Section names ought to be unique. Even if we represent them internally as unique, we have no way of distinguishing them on the user interface. I would close this issue as it does not affect the stability of the system.
