### ISSUE TITLE
Data Summary doesn't generate for survey forms

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#589]
When you create a survey, no data summary appears (presumably because the data summary creation was tied to the 'create checklist' function?). I believe we would want to maintain a data summary page for surveys that was identical to the one used for checklists - it would just of course no longer populate based on the total participants but based on the total form IDs instead. The only thing would to be careful of #586 , and make sure the data summary is populating based on the first column and not the location column.

**Comment by takinbo** [comment]
It's in the feature list and is being worked on.

**Comment by blynchNDI** [comment]
Ah ok no worries
