### ISSUE TITLE
Editing survey responses registers on the dashboard as another response

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#593]
If you submit part of your first survey entry, the dashboard will update to 1 complete. If you as a user modify this same entry, the dashboard will update to 2 complete, despite the fact that you have only filled in a single entry.

**Comment by takinbo** [comment]
Could you expatiate? The issue is not clear enough.

**Comment by blynchNDI** [comment]
For example suppose the pie chart goes up to 100, and participant 1 has submitted form serial number 001, and that this is the only the submission. The pie charts on the dashboard will correctly record 1 complete and 99 missing. However if an Apollo user goes to the "edit checklist" page and edits this exact submission (Participant 1 - Form Serial Number 001), returning to the dashboard shows 2 completions and 98 missing on the pie chart. Making modifications to this same submission (Participant 1 - Form Serial Number 001) ten times will causes the pie chart to read 10 completions and 90 missing, despite the fact we have only edited one submission (Participant 1 - Form Serial Number 001) and there are still 99 blanks ones
