### ISSUE TITLE
Issues with moment time

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#594]
Two potential issues with the moment column:
1. It seems that the column is reflective of roughly EST time rather than the timezone specified in settings.ini (unless this is somehow an intended feature where it is also to grab your current time)?
2. Perhaps somehow related to 1, I had an occurrence where despite an entry having been submitted today and the timestamp being today, filtering for it only worked if I put in tomorrow's date. Let me know if you need more detail for debugging

**Comment by takinbo** [comment]
Just like the message log, the date time shown is converted to the timezone of the browser viewing the page.
When filtering, you are filtering based on what is stored in the database. Which would be UTC. Can you give specific examples with the timezone for each example?

**Comment by blynchNDI** [comment]
Ah ok, didn't know that was possible with the first point. That's a good feature then.

With regards to the second, I've screenshot-ed below. The times being displayed are then presumably DC time. The settings.ini was set Belgrade local time, and the submissions should have been submitted sometime around evening-night Belgrade time (morning to afternoon DC time). Applying the date filter for the day after (October 22nd) caused these entries to appear, while filtering by today (October 21st) did not bring them up. This was observed while it was still the 21st in Belgrade.

![Screenshot from 2019-10-21 21-32-31](https://user-images.githubusercontent.com/31080607/67254302-5148e600-f44a-11e9-9757-16954e9d4521.png)

**Comment by takinbo** [comment]
#599 implements a fix for this by using the timezone defined in the settings of the application when displaying timestamps across the application. This is what makes the most sense as it creates confusion when it gets converted to the local timezone of the browser viewing the data. Filtering will also use the timezone as defined within the application settings.

**Comment by blynchNDI** [comment]
Very late in QAing this - it appears that the time now matches the time set by settings.ini, but the filtering issue still remains. For example, I tried submitting an entry today at 12:32pm ET, with the timezone set as Serbian time, meaning it displayed as 6:32pm Serbian time with today's date on the survey page. However filtering by today's date (17-12-2019) did not bring up the submission, whereas filtering by tomorrow's date did (18-12-2019). I can provide access to the test server I was trying it out on if it is not easily re-creatable

**Comment by blynchNDI** [comment]
Tested and all seems to be working well
