### ISSUE TITLE
Apollo not uploading large files

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#604]
The elections team has run into an issue where Apollo appears to not be accepting a file for upload because it is too large. The file is rejected on the upload screen as seen below. If the file is reduced to any given pair of columns it can be uploaded ok - it is only when a certain number of columns/characters are included that the file is rejected. I've sent over the file in question that is causing issues

![Screenshot from 2019-10-30 09-53-53](https://user-images.githubusercontent.com/31080607/67863941-36860980-fafb-11e9-928a-f72083fa3c10.png)

**Comment by takinbo** [comment]
Edited comments to remove information that may be confidential.

**Comment by blynchNDI** [comment]
Thanks for the help on this, it indeed wasn't an Apollo error. It actually occurred even without cloudflare on and ended up being an Nginx error. Adding the line `client_max_body_size 20M;` to `nginx.conf` on the server fixed it.
